Merge Feature/database structure into devel
mad201802/firstpass pull request #11
Opened 2022-11-01 21:41 UTC by lv042

2022-11-01 22:40 UTC, mad201802 requested changes
Bitte die in PR erstellten Kommentare bearbeiten. Bis auf das sieht das echt klasse aus! :)

2022-11-01 22:40 UTC, mad201802 commented on backend/src/main/java/database/drivers/SQLiteDriver.java
> +    static String url = "jdbc:sqlite:database.db";
Add this url to the constructor of the class

2022-11-01 22:40 UTC, mad201802 commented on backend/src/main/java/database/EncryptedDatabase.java
> +public class EncryptedDatabase {
Du kannst die Klasse in das "models" package verschieben und umbenennen (EncryptedModel). An sich ist das ja keine Datenbank :)

2022-11-01 22:40 UTC, mad201802 commented on backend/src/main/java/database/models/EntryModel.java
> +@DatabaseTable(tableName = "passwords")
Sollte man noch zu "entries" umbenennen.

2022-11-02 09:29 UTC, LeoLTM approved these changes
Passt 👍🏽

2022-11-02 10:26 UTC, mad201802 approved these changes
💯

2022-11-02 10:26 UTC, mad201802 commented on backend/.gitignore
> +*db
Hier fehlt noch der . (*.db)

2022-11-02 10:28 UTC, merged